runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /static/
  static_files: static/index.html
  upload: static/index.html

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

skip_files:
- community-dashboard-frontend/
- logs/

